# Generated by Django 4.2 on 2023-04-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0007_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Interesse',
            field=models.ManyToManyField(to='CadastroCliente.interesse'),
        ),
    ]
