# Generated by Django 4.2 on 2023-05-09 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0008_cliente_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Ativo',
            field=models.BooleanField(verbose_name='Usario Ativo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=250, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadastroCliente.profissoes', verbose_name='Profissão'),
        ),
    ]
